---
title: "SP500 Quant Screener"
author: "Kyle Evan Murphy"
date: "10/19/2018"
output: html_document
code_folding: "hide"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Prerequisites

These are the following packages that will be used to conduct the SP500 stock analysis:
```{r packages, echo=TRUE, message=FALSE, warning=FALSE}
library(quantmod)   # get stock prices, stock analysis functions
library(xts)        # extensible time series functions
library(rvest)      # web scraping
library(tidyverse)  # ggplot2, purrr, dplyr, tidyr, readr, tibble
library(stringr)    # working with strings
library(forcats)    # working with factors
library(lubridate)  # working with dates in tibble / data frames
library(plotly)     # interactive plots
library(corrplot)   # visualizing correlation plots
```

## Quantmod Analysis

We are going to use quantmod to download and view the SP500 ETF ("SPY") using data from yahoo finance. 
```{r echo=TRUE, message=FALSE, warning=FALSE}
getSymbols(
  "SPY",
  src = "yahoo",
  auto.assign = TRUE,  # automatically assign a variable with the ticker name
  from = "2007-01-01", # start date
  to = Sys.Date()      # today's date
  )
  chartSeries(SPY)
```


Let's quickly check the class of our SPY variable
```{r}
SPY %>% class()
```

